spring:
  datasource:
    url: jdbc:postgresql://bd:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none   # la base existe déjà (collector + init.sql)
    show-sql: true
  


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
server:
  port: 8080
