apiVersion: v1
data:
  COINGECKO_API_URL: https://api.coingecko.com/api/v3
  DB_NAME: crypto_db
  DB_USER: crypto_user
  FRONTEND_URL: http://localhost:3000
  JWT_EXPIRATION: '86400000'
  MAIL_FROM: math.dels84@gmail.com
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: '587'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"COINGECKO_API_URL":"https://api.coingecko.com/api/v3","DB_NAME":"crypto_db","DB_USER":"crypto_user","FRONTEND_URL":"http://localhost:3000","JWT_EXPIRATION":"86400000","MAIL_FROM":"math.dels84@gmail.com","MAIL_HOST":"smtp.gmail.com","MAIL_PORT":"587"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"app-config","namespace":"project-crypto"}}

      '
  name: app-config
  namespace: project-crypto
