apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"collector","namespace":"project-crypto"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"collector"}},"template":{"metadata":{"labels":{"app":"collector"}},"spec":{"containers":[{"env":[{"name":"SERVER_PORT","value":"8081"},{"name":"SPRING_DATASOURCE_URL","value":"jdbc:postgresql://postgres:5432/crypto_db"},{"name":"SPRING_DATASOURCE_USERNAME","value":"crypto_user"},{"name":"SPRING_DATASOURCE_PASSWORD","valueFrom":{"secretKeyRef":{"key":"POSTGRES_PASSWORD","name":"postgres-secret"}}},{"name":"COINGECKO_API_URL","valueFrom":{"configMapKeyRef":{"key":"COINGECKO_API_URL","name":"app-config"}}},{"name":"SPRING_MAIL_HOST","valueFrom":{"configMapKeyRef":{"key":"MAIL_HOST","name":"app-config"}}},{"name":"SPRING_MAIL_PORT","valueFrom":{"configMapKeyRef":{"key":"MAIL_PORT","name":"app-config"}}},{"name":"SPRING_MAIL_USERNAME","valueFrom":{"secretKeyRef":{"key":"MAIL_USERNAME","name":"app-secrets"}}},{"name":"SPRING_MAIL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"MAIL_PASSWORD","name":"app-secrets"}}},{"name":"APP_MAIL_FROM","valueFrom":{"configMapKeyRef":{"key":"MAIL_FROM","name":"app-config"}}},{"name":"APP_MAIL_FRONTENDURL","valueFrom":{"configMapKeyRef":{"key":"FRONTEND_URL","name":"app-config"}}}],"image":"project-crypto-collector:latest","imagePullPolicy":"IfNotPresent","name":"collector","ports":[{"containerPort":8081}]}]}}}}

      '
  name: collector
  namespace: project-crypto
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: collector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-01-08T00:44:18+01:00'
      labels:
        app: collector
    spec:
      containers:
        - env:
            - name: SERVER_PORT
              value: '8081'
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/crypto_db
            - name: SPRING_DATASOURCE_USERNAME
              value: crypto_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
            - name: COINGECKO_API_URL
              valueFrom:
                configMapKeyRef:
                  key: COINGECKO_API_URL
                  name: app-config
            - name: SPRING_MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MAIL_HOST
                  name: app-config
            - name: SPRING_MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MAIL_PORT
                  name: app-config
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MAIL_USERNAME
                  name: app-secrets
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MAIL_PASSWORD
                  name: app-secrets
            - name: APP_MAIL_FROM
              valueFrom:
                configMapKeyRef:
                  key: MAIL_FROM
                  name: app-config
            - name: APP_MAIL_FRONTENDURL
              valueFrom:
                configMapKeyRef:
                  key: FRONTEND_URL
                  name: app-config
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MAIL_HOST
                  name: app-config
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MAIL_PORT
                  name: app-config
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MAIL_USERNAME
                  name: app-secrets
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MAIL_PASSWORD
                  name: app-secrets
            - name: MAIL_FROM
              valueFrom:
                configMapKeyRef:
                  key: MAIL_FROM
                  name: app-config
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  key: FRONTEND_URL
                  name: app-config
          image: project-crypto-collector:latest
          imagePullPolicy: IfNotPresent
          name: collector
          ports:
            - containerPort: 8081
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
