apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"front","namespace":"project-crypto"},"spec":{"ports":[{"port":3000,"targetPort":3000}],"selector":{"app":"front"}}}

      '
  name: front
  namespace: project-crypto
spec:
  clusterIP: 10.97.227.65
  clusterIPs:
    - 10.97.227.65
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: front
  sessionAffinity: None
  type: ClusterIP
